[2024-12-10T18:07:26.834-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T18:07:26.840-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.extract_transform manual__2024-12-10T23:55:01.372292+00:00 [queued]>
[2024-12-10T18:07:26.845-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.extract_transform manual__2024-12-10T23:55:01.372292+00:00 [queued]>
[2024-12-10T18:07:26.845-0600] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2024-12-10T18:07:26.859-0600] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_transform> on 2024-12-10 23:55:01.372292+00:00
[2024-12-10T18:07:26.864-0600] {standard_task_runner.py:72} INFO - Started process 5678 to run task
[2024-12-10T18:07:26.866-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl', 'extract_transform', 'manual__2024-12-10T23:55:01.372292+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp2azef1o6']
[2024-12-10T18:07:26.867-0600] {standard_task_runner.py:105} INFO - Job 21: Subtask extract_transform
[2024-12-10T18:07:26.896-0600] {task_command.py:467} INFO - Running <TaskInstance: weather_etl.extract_transform manual__2024-12-10T23:55:01.372292+00:00 [running]> on host Shanmukhi.
[2024-12-10T18:07:26.940-0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='extract_transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T23:55:01.372292+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T23:55:01.372292+00:00'
[2024-12-10T18:07:26.941-0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T18:07:26.942-0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T18:07:26.942-0600] {logging_mixin.py:190} INFO - Current task name:extract_transform state:running start_date:2024-12-11 00:07:26.841402+00:00
[2024-12-10T18:07:26.942-0600] {logging_mixin.py:190} INFO - Dag name:weather_etl and current dag run status:running
[2024-12-10T18:07:26.942-0600] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T18:07:28.045-0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/weather_dag.py", line 51, in run_extract_transform
    context['task_instance'].xcom_push(key='current_df', value=current_df.to_json())
                                                               ^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/core/generic.py", line 2702, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 200, in to_json
    s = writer(
        ^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 256, in __init__
    self._format_axes()
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 312, in _format_axes
    raise ValueError(
ValueError: DataFrame index must be unique for orient='columns'.
[2024-12-10T18:07:28.051-0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T18:07:28.051-0600] {logging_mixin.py:190} INFO - Task start:2024-12-11 00:07:26.841402+00:00 end:2024-12-11 00:07:28.050995+00:00 duration:1.209593
[2024-12-10T18:07:28.051-0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_transform> dag:<DAG: weather_etl> dagrun:<DagRun weather_etl @ 2024-12-10 23:55:01.372292+00:00: manual__2024-12-10T23:55:01.372292+00:00, state:running, queued_at: 2024-12-11 00:02:21.176595+00:00. externally triggered: True>
[2024-12-10T18:07:28.051-0600] {logging_mixin.py:190} INFO - Failure caused by DataFrame index must be unique for orient='columns'.
[2024-12-10T18:07:28.052-0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_etl, task_id=extract_transform, run_id=manual__2024-12-10T23:55:01.372292+00:00, execution_date=20241210T235501, start_date=20241211T000726, end_date=20241211T000728
[2024-12-10T18:07:28.063-0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T18:07:28.063-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task extract_transform (DataFrame index must be unique for orient='columns'.; 5678)
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/weather_dag.py", line 51, in run_extract_transform
    context['task_instance'].xcom_push(key='current_df', value=current_df.to_json())
                                                               ^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/core/generic.py", line 2702, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 200, in to_json
    s = writer(
        ^^^^^^^
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 256, in __init__
    self._format_axes()
  File "/root/airflow_env/lib/python3.12/site-packages/pandas/io/json/_json.py", line 312, in _format_axes
    raise ValueError(
ValueError: DataFrame index must be unique for orient='columns'.
[2024-12-10T18:07:28.088-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T18:07:28.099-0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T18:07:28.107-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
